# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('food_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_is_menu', models.BooleanField()),
                ('creator_user_id', models.IntegerField()),
                ('list_name', models.TextField()),
                ('list_description', models.TextField()),
                ('list_follower', models.ManyToManyField(to='kwue.UserModel')),
            ],
        ),
        migrations.AddField(
            model_name='foodservermodel',
            name='food_server_email',
            field=models.EmailField(default=10, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodservermodel',
            name='food_server_password',
            field=models.CharField(default=12, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followermodel',
            name='food_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwue.ListModel'),
        ),
        migrations.AddField(
            model_name='followermodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwue.UserModel'),
        ),
    ]
