# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0002_auto_20161022_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followermodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='listmodel',
            name='creator_user_id',
        ),
        migrations.AddField(
            model_name='listmodel',
            name='owner_user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kwue.UserModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='list_follower',
            field=models.ManyToManyField(related_name='followers', to='kwue.UserModel'),
        ),
    ]
