# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0004_auto_20161022_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('consumed_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwue.FoodModel')),
                ('consumer_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwue.UserModel')),
            ],
        ),
        migrations.DeleteModel(
            name='EatingPreferenceModel',
        ),
    ]
