# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kwue', '0005_auto_20161022_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='child_id',
            new_name='child_comment',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='food_id',
            new_name='commented_food',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='commit_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='food_server_id',
            new_name='food_server',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='user_id',
            new_name='owner_user',
        ),
        migrations.RenameField(
            model_name='foodmodel',
            old_name='food_server_id',
            new_name='food_owner',
        ),
        migrations.RenameField(
            model_name='listmodel',
            old_name='owner_user_id',
            new_name='owner_user',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_image',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_vote',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='food_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodservermodel',
            name='food_server_image',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder'),
        ),
        migrations.AddField(
            model_name='foodservermodel',
            name='food_server_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listmodel',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder'),
        ),
    ]
