# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kwue', '0006_auto_20161023_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='owner_user',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
