# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0007_auto_20161023_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='child_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kwue.CommentModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_image',
            field=models.ImageField(null=True, upload_to=b'pic_folder'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='food_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodservermodel',
            name='food_server_rate',
            field=models.IntegerField(default=0),
        ),
    ]
