# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0008_auto_20161023_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listmodel',
            old_name='food_list_id',
            new_name='list_id',
        ),
    ]
