# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0009_auto_20161023_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listmodel',
            name='list_food',
        ),
        migrations.RemoveField(
            model_name='listmodel',
            name='object_id',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='owner_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
