# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0010_auto_20161023_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_surname',
            new_name='user_nick',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='food_server',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='food_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwue.UserModel'),
        ),
        migrations.DeleteModel(
            name='FoodServerModel',
        ),
    ]
