# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kwue', '0012_auto_20161023_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kwue.TreeItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='child_comment',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='commented_object_id',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_image',
            field=models.ImageField(null=True, upload_to='pic_folder'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='food_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder'),
        ),
    ]
