# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kwue', '0013_auto_20161023_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='treeitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='commented_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kwue.CommentModel'),
        ),
        migrations.DeleteModel(
            name='TreeItem',
        ),
    ]
