# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0017_commenttree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='commented_object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
