# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0019_auto_20161023_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttree',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='commenttree',
            name='parent',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='level',
            new_name='mptt_level',
        ),
        migrations.DeleteModel(
            name='CommentTree',
        ),
    ]
