# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0020_auto_20161023_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder'),
        ),
    ]
