# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0021_auto_20161023_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='created_date',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='parent',
            new_name='comment_parent',
        ),
        migrations.RenameField(
            model_name='listmodel',
            old_name='list_is_menu',
            new_name='list_menu',
        ),
        migrations.RenameField(
            model_name='listmodel',
            old_name='owner_user',
            new_name='list_owner',
        ),
        migrations.RemoveField(
            model_name='listmodel',
            name='content_type',
        ),
        migrations.AddField(
            model_name='listmodel',
            name='list_content',
            field=models.ManyToManyField(related_name='foods', to='kwue.FoodModel'),
        ),
    ]
