# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0022_auto_20161027_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumedfood',
            name='consumed_food',
        ),
        migrations.RemoveField(
            model_name='consumedfood',
            name='consumer_food',
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='food_consumption',
            field=models.ManyToManyField(related_name='history', to='kwue.UserModel'),
        ),
        migrations.DeleteModel(
            name='ConsumedFood',
        ),
    ]
