# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0024_auto_20161027_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodmodel',
            old_name='food_consumption',
            new_name='user_history',
        ),
    ]
