# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0026_auto_20161105_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='food_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.URLField(),
        ),
    ]
