# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0027_auto_20161105_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='consumptionhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
