# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0028_auto_20161105_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionhistory',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
