# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0030_auto_20161105_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptionhistory',
            name='text',
        ),
    ]
