# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0031_remove_consumptionhistory_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionhistory',
            name='food_rate',
            field=models.IntegerField(default=0),
        ),
    ]
