# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0032_consumptionhistory_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='calorie_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='carbonhydrate_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='fat_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='fiber_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='protein_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='serving_weight_grams',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='sugar_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
