# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0034_foodmodel_food_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='semantic_tag_item',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='semantic_tag_item_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='semantic_tag_item_label',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='tag_label',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='tagged_food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kwue.FoodModel'),
            preserve_default=False,
        ),
    ]
