# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0035_auto_20161106_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodmodel',
            old_name='carbonhydrate_value',
            new_name='carbohydrate_value',
        ),
    ]
