# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0038_foodmodel_ingredient_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('ingredient_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='ingredient_list',
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='ingredient_list',
            field=models.ManyToManyField(to='kwue.IngredientModel'),
        ),
    ]
