# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0039_auto_20161113_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodel',
            name='biotin',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='chromium',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='clouride',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='iodine',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='molybdenum',
        ),
    ]
