# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kwue', '0041_auto_20161113_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='tagged_food',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='allergic_ingredients',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='preference_tags',
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='tagged_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='unwanted_ingredients',
            field=models.ManyToManyField(related_name='wantedfoods', to='kwue.IngredientModel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='wanted_ingredients',
            field=models.ManyToManyField(related_name='unwantedfoods', to='kwue.IngredientModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='commented_object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='food_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwue.UserModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='FoodSerModel',
        ),
    ]
