# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwue', '0042_auto_20161116_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptionhistory',
            name='food_rate',
        ),
    ]
